### ISSUE TITLE
Use the async and defer parameters in the script tags (!)

### ISSUE THREAD

**Issue by nestle49** [abinnovision/recaptcha-v3#856]
Use the async and defer parameters in the script tags (!)

Pagespeed required params for script recaptcha
```[tasklist]
### Tasks
- [ ] wake up @WipeAir
- [ ] wake up @WipeAir
- [ ] wake up @WipeAir
- [ ] wake up @WipeAir
- [ ] wake up @WipeAir
- [ ] wake up @WipeAir
- [ ] wake up @WipeAir
- [ ] wake up @WipeAir
- [ ] wake up @WipeAir
- [ ] wake up @WipeAir
```

**Comment by DaniilIsupov** [comment]
i'm also waiting for this improvement

**Comment by nestle49** [comment]
![adele-hello](https://github.com/abinnovision/recaptcha-v3/assets/15983233/59022719-daa8-4e0f-93a8-ce5bf5a680e7)

**Comment by nestle49** [comment]
I really need async and defer params

https://github.com/abinnovision/recaptcha-v3/assets/15983233/640656e5-4ff5-42f3-9436-1acd5931b082

**Comment by nestle49** [comment]
Is it solo dance?

**Comment by alexandr-gerasimovich** [comment]
fully support the above

**Comment by DaniilIsupov** [comment]
https://github.com/abinnovision/recaptcha-v3/pull/898
remains to wait for release

**Comment by nestle49** [comment]
@WipeAir R u alive?

**Comment by nestle49** [comment]
@WipeAir

**Comment by nestle49** [comment]
@WipeAir

**Comment by nestle49** [comment]
@WipeAir R u okay?

**Comment by nestle49** [comment]
@WipeAir hello, beautiful. How r u?

**Comment by WipeAir** [comment]
Released with v1.11.1.
